DUK_USE_BUFFEROBJECT_SUPPORT: true
DUK_USE_ENCODING_BUILTINS: true
DUK_USE_DUKTAPE_BUILTIN: true
DUK_USE_HEX_SUPPORT: true
DUK_USE_DATE_GET_NOW: esp32_duktape_get_now
DUK_USE_GET_RANDOM_DOUBLE: esp32_duktape_random_double

DUK_USE_VERBOSE_ERRORS: true
DUK_USE_TRACEBACKS: true
DUK_USE_AUGMENT_ERROR_CREATE: true
DUK_USE_FUNC_FILENAME_PROPERTY: true
DUK_USE_PC2LINE: true

#DUK_USE_REFERENCE_COUNTING: false
#DUK_USE_DOUBLE_LINKED_HEAP: false

DUK_USE_ROM_STRINGS: true
DUK_USE_ROM_OBJECTS: true
DUK_USE_ROM_GLOBAL_INHERIT: true

DUK_USE_FAST_REFCOUNT_DEFAULT: true
DUK_USE_BASE64_SUPPORT: true

